ALTER TABLE customers ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE events ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stream_credentials ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE viewer_tokens ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;